spring:
  profiles:
    active: local
  application:
    name: products-microservice

server:
  port: 8080

logging:
  level:
    root: info
    org.springframework.wen: info
    org.hibernate.SQL: debug
    org.hibernate.type: debug
    org.hibernate.type.descriptor.BasicBinder: debug


cronos:
  yugabyte:
    keyspace: cronos
    hostname: 127.0.0.1
    port: 9042
