cronos:
  yugabyte:
    keyspace: cronos
    hostname: ${YUGABYTE_IP}
    port: 9042

spring:
  #profiles:
   # active: local
  application:
    name: checkout-microservice
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
