cronos:
  yugabyte:
    keyspace: cronos
    hostname: yb-tservers.yb-demo-us-east1-b.svc.cluster.local
    port: 9042

spring:
  #profiles:
   # active: local
  application:
    name: checkout-microservice
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
