---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  annotations:
    autoscaling.knative.dev/minScale: "1"
  labels:
    apps.tanzu.vmware.com/workload-type: web
  name: products-microservice
spec:
  env:
  - name: "EUREKA_URI"
    value: "http://eureka-default.gkelabeast.tap.fynesy.com/eureka"
  - name: "YUGABYTE_IP"
    value: "34.138.140.119"
  #- name: "yugabyte.sql.datasource.url"
  #  value: "yugabyte.sql.datasource.url: jdbc:postgresql://yb-tservers.yb-demo.svc.cluster.local:5433/yugabyte"
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  source:
    git:
      ref:
        branch: master
      url: https://github.com/tfynes-pivotal/yugastore-java
    subPath: products-microservice 
